#!/usr/bin/env python3
"""Build browser-specific extension packages for Chrome and Firefox.

Usage:
    python build.py [--target chrome|firefox|all] [--repo PATH]

Produces dist/chrome/ and/or dist/firefox/ with the correct manifest
and Pyodide configuration for each browser. Creates submission-ready
ZIP files in dist/.

Firefox builds bundle Pyodide locally (AMO forbids remote code).
Chrome builds use the jsDelivr CDN.
"""

import argparse
import json
import os
import shutil
import sys
import urllib.request
import zipfile
from pathlib import Path

PYODIDE_VERSION = "0.27.7"
PYODIDE_CDN = f"https://cdn.jsdelivr.net/pyodide/v{PYODIDE_VERSION}/full"

# Minimal Pyodide files needed to run offline (Firefox/AMO).
PYODIDE_ASSETS = [
    "pyodide.asm.js",
    "pyodide.asm.wasm",
    "python_stdlib.zip",
    "pyodide-lock.json",
]

EXT_DIR = Path(__file__).parent
SHARED_FILES = [
    "popup.html",
    "popup.js",
    "background.js",
    "python_bundle.js",
    "pyodide.js",
]
SHARED_DIRS = ["icons"]


def ensure_bundle(repo: Path) -> None:
    """Run bundle.py if python_bundle.js is missing."""
    bundle_js = EXT_DIR / "python_bundle.js"
    pyodide_js = EXT_DIR / "pyodide.js"
    if not bundle_js.exists() or not pyodide_js.exists():
        print("Running bundle.py to generate python_bundle.js …")
        import subprocess

        subprocess.check_call(
            [sys.executable, str(EXT_DIR / "bundle.py"), str(repo)]
        )


def download_pyodide_assets(dest: Path) -> None:
    """Download the Pyodide runtime files for local/offline use."""
    dest.mkdir(parents=True, exist_ok=True)
    for name in PYODIDE_ASSETS:
        target = dest / name
        if target.exists():
            print(f"  Already present: {name}")
            continue
        url = f"{PYODIDE_CDN}/{name}"
        print(f"  Downloading {name} …")
        urllib.request.urlretrieve(url, str(target))
        size_kb = target.stat().st_size // 1024
        print(f"    {size_kb:,} KB")


def copy_shared(dest: Path) -> None:
    """Copy shared extension files into a target build directory."""
    dest.mkdir(parents=True, exist_ok=True)
    for name in SHARED_FILES:
        src = EXT_DIR / name
        if not src.exists():
            raise FileNotFoundError(f"Missing required file: {src}")
        shutil.copy2(src, dest / name)
    for d in SHARED_DIRS:
        src = EXT_DIR / d
        if src.is_dir():
            shutil.copytree(src, dest / d, dirs_exist_ok=True)


def write_config(dest: Path, *, local_pyodide: bool) -> None:
    """Write config.js with build-specific Pyodide settings."""
    if local_pyodide:
        # Firefox: use extension-local Pyodide files
        config = {
            "PYODIDE_INDEX_URL": "__EXTENSION_URL__pyodide/",
            "PYODIDE_LOCAL": True,
        }
    else:
        # Chrome: use CDN
        config = {
            "PYODIDE_INDEX_URL": f"{PYODIDE_CDN}/",
            "PYODIDE_LOCAL": False,
        }

    js = (
        "// Auto-generated by build.py — do not edit.\n"
        f"const EXT_CONFIG = {json.dumps(config, indent=2)};\n"
    )
    (dest / "config.js").write_text(js, encoding="utf-8")


def patch_popup_html(dest: Path) -> None:
    """Inject config.js script tag into popup.html before other scripts."""
    html_path = dest / "popup.html"
    html = html_path.read_text(encoding="utf-8")
    # Insert config.js before pyodide.js
    html = html.replace(
        '<script src="pyodide.js"></script>',
        '<script src="config.js"></script>\n  <script src="pyodide.js"></script>',
    )
    html_path.write_text(html, encoding="utf-8")


def build_chrome(dist: Path) -> Path:
    """Build the Chrome/Edge/Brave extension."""
    dest = dist / "chrome"
    if dest.exists():
        shutil.rmtree(dest)

    print("\n── Building Chrome extension ──")
    copy_shared(dest)
    shutil.copy2(EXT_DIR / "manifest.chrome.json", dest / "manifest.json")
    write_config(dest, local_pyodide=False)
    patch_popup_html(dest)

    print(f"  Output: {dest}")
    return dest


def build_firefox(dist: Path) -> Path:
    """Build the Firefox extension with locally bundled Pyodide."""
    dest = dist / "firefox"
    if dest.exists():
        shutil.rmtree(dest)

    print("\n── Building Firefox extension ──")
    copy_shared(dest)
    shutil.copy2(EXT_DIR / "manifest.firefox.json", dest / "manifest.json")
    write_config(dest, local_pyodide=True)
    patch_popup_html(dest)

    # Download Pyodide runtime for offline use
    print("  Downloading Pyodide assets for local bundling …")
    download_pyodide_assets(dest / "pyodide")

    # Firefox CSP: remove CDN connect-src since we're local now
    manifest_path = dest / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    csp = manifest["content_security_policy"]["extension_pages"]
    # Keep self but remove external connect-src for Pyodide
    csp = csp.replace(
        "connect-src 'self' https://cdn.jsdelivr.net https://files.pythonhosted.org",
        "connect-src 'self'",
    )
    manifest["content_security_policy"]["extension_pages"] = csp
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    print(f"  Output: {dest}")
    return dest


def create_zip(src_dir: Path, zip_path: Path) -> None:
    """Create a ZIP file from a directory (for store submission)."""
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in sorted(src_dir.rglob("*")):
            if path.is_file():
                zf.write(path, path.relative_to(src_dir))
    size_mb = zip_path.stat().st_size / (1024 * 1024)
    print(f"  ZIP: {zip_path} ({size_mb:.1f} MB)")


def create_source_archive(dist: Path) -> None:
    """Create a source code archive for AMO review.

    AMO requires source code submission when the extension contains
    generated/minified code (python_bundle.js is generated by bundle.py).
    """
    zip_path = dist / "slop-guard-source.zip"
    print(f"\n── Creating source archive for AMO review ──")

    # Include the files reviewers need to reproduce the build
    source_files = [
        "bundle.py",
        "build.py",
        "popup.html",
        "popup.js",
        "background.js",
        "manifest.chrome.json",
        "manifest.firefox.json",
        "update.sh",
        "update.ps1",
        "README.md",
    ]

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for name in source_files:
            src = EXT_DIR / name
            if src.exists():
                zf.write(src, f"slop-guard-ext/{name}")
        # Include icons
        for icon in (EXT_DIR / "icons").glob("*.png"):
            zf.write(icon, f"slop-guard-ext/icons/{icon.name}")
        # Include parent project source (needed to reproduce python_bundle.js)
        repo_src = EXT_DIR.parent / "src" / "slop_guard"
        if repo_src.is_dir():
            for path in sorted(repo_src.rglob("*")):
                if path.is_file():
                    rel = path.relative_to(EXT_DIR.parent)
                    zf.write(path, f"slop-guard/{rel}")
        # Include pyproject.toml for version info
        pyproject = EXT_DIR.parent / "pyproject.toml"
        if pyproject.exists():
            zf.write(pyproject, "slop-guard/pyproject.toml")

    size_kb = zip_path.stat().st_size // 1024
    print(f"  Source archive: {zip_path} ({size_kb} KB)")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build Slop Guard extension")
    parser.add_argument(
        "--target",
        choices=["chrome", "firefox", "all"],
        default="all",
        help="Which browser to build for (default: all)",
    )
    parser.add_argument(
        "--repo",
        type=Path,
        default=EXT_DIR.parent,
        help="Path to slop-guard repository root",
    )
    parser.add_argument(
        "--no-zip",
        action="store_true",
        help="Skip creating ZIP archives",
    )
    args = parser.parse_args()

    ensure_bundle(args.repo)

    dist = EXT_DIR / "dist"
    dist.mkdir(exist_ok=True)

    targets = (
        ["chrome", "firefox"] if args.target == "all" else [args.target]
    )

    for target in targets:
        if target == "chrome":
            dest = build_chrome(dist)
        else:
            dest = build_firefox(dist)

        if not args.no_zip:
            create_zip(dest, dist / f"slop-guard-{target}.zip")

    if "firefox" in targets and not args.no_zip:
        create_source_archive(dist)

    print("\n── Done ──")
    print("Chrome:  Load dist/chrome/ as unpacked extension")
    print("Firefox: Load dist/firefox/manifest.json as temporary add-on")
    if not args.no_zip:
        print("AMO:     Upload dist/slop-guard-firefox.zip + dist/slop-guard-source.zip")


if __name__ == "__main__":
    main()
