#!/usr/bin/env python3
"""Build browser-specific extension packages for Chrome and Firefox.

Usage:
    uv run build.py [--target chrome|firefox|all] [--repo PATH]

Produces dist/chrome/ and/or dist/firefox/ with the correct manifest
and Pyodide configuration for each browser. Creates submission-ready
ZIP files in dist/.

Both Chrome and Firefox bundle Pyodide locally.
"""

import argparse
import json
import shutil
import subprocess
import sys
import urllib.request
import zipfile
from pathlib import Path

PYODIDE_VERSION = "0.27.7"
PYODIDE_CDN = f"https://cdn.jsdelivr.net/pyodide/v{PYODIDE_VERSION}/full"

# Minimal Pyodide files needed to run offline.
PYODIDE_ASSETS = [
    "pyodide.asm.js",
    "pyodide.asm.wasm",
    "python_stdlib.zip",
    "pyodide-lock.json",
]

EXT_DIR = Path(__file__).parent
DEFAULT_REPO = EXT_DIR.parent
SHARED_FILES = [
    "popup.html",
    "popup.js",
    "background.js",
    "python_bundle.js",
    "pyodide.js",
]
SHARED_DIRS = ["icons"]


def default_repo_path() -> Path:
    """Return the default repository root for local builds."""
    return DEFAULT_REPO


def _bundle_inputs(repo: Path) -> list[Path]:
    """Return the files that affect the generated Python bundle."""
    inputs = [
        EXT_DIR / "bundle.py",
        repo / "pyproject.toml",
    ]
    src_dir = repo / "src" / "slop_guard"
    if src_dir.is_dir():
        inputs.extend(
            path
            for path in src_dir.rglob("*")
            if path.is_file() and path.suffix in {".py", ".jsonl"}
        )
    return inputs


def bundle_needs_refresh(repo: Path) -> bool:
    """Return whether python_bundle.js or pyodide.js should be regenerated."""
    bundle_js = EXT_DIR / "python_bundle.js"
    pyodide_js = EXT_DIR / "pyodide.js"
    version_marker = EXT_DIR / ".pyodide-version"
    outputs = [bundle_js, pyodide_js, version_marker]

    if any(not path.exists() for path in outputs):
        return True
    if version_marker.read_text(encoding="utf-8").strip() != PYODIDE_VERSION:
        return True

    inputs = _bundle_inputs(repo)
    if not inputs:
        return True

    newest_input = max(path.stat().st_mtime for path in inputs if path.exists())
    oldest_output = min(path.stat().st_mtime for path in outputs)

    # Custom repositories should always regenerate the bundle instead of
    # reusing whatever was last built from the default checkout.
    return (
        repo.resolve() != default_repo_path().resolve() or newest_input > oldest_output
    )


def ensure_bundle(repo: Path) -> None:
    """Run bundle.py when the generated bundle is missing or stale."""
    if not bundle_needs_refresh(repo):
        return

    print("Refreshing python bundle...")
    subprocess.check_call(
        [sys.executable, str(EXT_DIR / "bundle.py"), str(repo)],
        cwd=EXT_DIR,
    )


def download_pyodide_assets(dest: Path) -> None:
    """Download the Pyodide runtime files for local/offline use."""
    dest.mkdir(parents=True, exist_ok=True)
    for name in PYODIDE_ASSETS:
        target = dest / name
        if target.exists():
            print(f"  Already present: {name}")
            continue
        url = f"{PYODIDE_CDN}/{name}"
        print(f"  Downloading {name} ...")
        urllib.request.urlretrieve(url, str(target))
        size_kb = target.stat().st_size // 1024
        print(f"    {size_kb:,} KB")


def copy_shared(dest: Path) -> None:
    """Copy shared extension files into a target build directory."""
    dest.mkdir(parents=True, exist_ok=True)
    for name in SHARED_FILES:
        src = EXT_DIR / name
        if not src.exists():
            raise FileNotFoundError(f"Missing required file: {src}")
        shutil.copy2(src, dest / name)
    for name in SHARED_DIRS:
        src = EXT_DIR / name
        if src.is_dir():
            shutil.copytree(src, dest / name, dirs_exist_ok=True)


def write_config(dest: Path, *, local_pyodide: bool) -> None:
    """Write config.js with build-specific Pyodide settings."""
    if local_pyodide:
        config = {
            "PYODIDE_INDEX_URL": "__EXTENSION_URL__pyodide/",
            "PYODIDE_LOCAL": True,
        }
    else:
        config = {
            "PYODIDE_INDEX_URL": f"{PYODIDE_CDN}/",
            "PYODIDE_LOCAL": False,
        }

    js = (
        "// Auto-generated by build.py - do not edit.\n"
        f"const EXT_CONFIG = {json.dumps(config, indent=2)};\n"
    )
    (dest / "config.js").write_text(js, encoding="utf-8")


def patch_popup_html(dest: Path) -> None:
    """Inject config.js into popup.html before the runtime scripts."""
    html_path = dest / "popup.html"
    html = html_path.read_text(encoding="utf-8")
    html = html.replace(
        '<script src="pyodide.js"></script>',
        '<script src="config.js"></script>\n  <script src="pyodide.js"></script>',
    )
    html_path.write_text(html, encoding="utf-8")


def build_chrome(dist: Path) -> Path:
    """Build the Chrome/Edge/Brave extension with locally bundled Pyodide."""
    dest = dist / "chrome"
    if dest.exists():
        shutil.rmtree(dest)

    print("\n-- Building Chrome extension --")
    copy_shared(dest)
    shutil.copy2(EXT_DIR / "manifest.chrome.json", dest / "manifest.json")
    write_config(dest, local_pyodide=True)
    patch_popup_html(dest)
    print("  Downloading Pyodide assets for local bundling ...")
    download_pyodide_assets(dest / "pyodide")

    print(f"  Output: {dest}")
    return dest


def build_firefox(dist: Path) -> Path:
    """Build the Firefox extension with locally bundled Pyodide."""
    dest = dist / "firefox"
    if dest.exists():
        shutil.rmtree(dest)

    print("\n-- Building Firefox extension --")
    copy_shared(dest)
    shutil.copy2(EXT_DIR / "manifest.firefox.json", dest / "manifest.json")
    write_config(dest, local_pyodide=True)
    patch_popup_html(dest)

    print("  Downloading Pyodide assets for local bundling ...")
    download_pyodide_assets(dest / "pyodide")

    print(f"  Output: {dest}")
    return dest


def create_zip(src_dir: Path, zip_path: Path) -> None:
    """Create a ZIP file from a directory for store submission."""
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in sorted(src_dir.rglob("*")):
            if path.is_file():
                zf.write(path, path.relative_to(src_dir))
    size_mb = zip_path.stat().st_size / (1024 * 1024)
    print(f"  ZIP: {zip_path} ({size_mb:.1f} MB)")


def create_source_archive(dist: Path, repo: Path) -> None:
    """Create a source code archive for AMO review."""
    zip_path = dist / "slop-guard-source.zip"
    print("\n-- Creating source archive for AMO review --")

    source_files = [
        "config.js",
        "bundle.py",
        "build.py",
        "popup.html",
        "popup.js",
        "background.js",
        "manifest.chrome.json",
        "manifest.firefox.json",
        "update.sh",
        "update.ps1",
        "README.md",
    ]

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for name in source_files:
            src = EXT_DIR / name
            if src.exists():
                zf.write(src, f"slop-guard-ext/{name}")

        for icon in (EXT_DIR / "icons").glob("*.png"):
            zf.write(icon, f"slop-guard-ext/icons/{icon.name}")

        repo_src = repo / "src" / "slop_guard"
        if repo_src.is_dir():
            for path in sorted(repo_src.rglob("*")):
                if path.is_file():
                    rel = path.relative_to(repo)
                    zf.write(path, f"slop-guard/{rel}")

        pyproject = repo / "pyproject.toml"
        if pyproject.exists():
            zf.write(pyproject, "slop-guard/pyproject.toml")

    size_kb = zip_path.stat().st_size // 1024
    print(f"  Source archive: {zip_path} ({size_kb} KB)")


def main() -> None:
    """Build the requested browser targets."""
    parser = argparse.ArgumentParser(description="Build Slop Guard extension")
    parser.add_argument(
        "--target",
        choices=["chrome", "firefox", "all"],
        default="all",
        help="Which browser to build for (default: all)",
    )
    parser.add_argument(
        "--repo",
        type=Path,
        default=default_repo_path(),
        help="Path to slop-guard repository root",
    )
    parser.add_argument(
        "--no-zip",
        action="store_true",
        help="Skip creating ZIP archives",
    )
    args = parser.parse_args()

    repo = args.repo.resolve()
    ensure_bundle(repo)

    dist = EXT_DIR / "dist"
    dist.mkdir(exist_ok=True)
    targets = ["chrome", "firefox"] if args.target == "all" else [args.target]

    for target in targets:
        if target == "chrome":
            dest = build_chrome(dist)
        else:
            dest = build_firefox(dist)

        if not args.no_zip:
            create_zip(dest, dist / f"slop-guard-{target}.zip")

    if "firefox" in targets and not args.no_zip:
        create_source_archive(dist, repo)

    print("\n-- Done --")
    print("Chrome:  Load dist/chrome/ as unpacked extension")
    print("Firefox: Load dist/firefox/manifest.json as temporary add-on")
    if not args.no_zip:
        print(
            "AMO:     Upload dist/slop-guard-firefox.zip + dist/slop-guard-source.zip"
        )


if __name__ == "__main__":
    main()
